import '../classes/bulgarianspl.dart';
import '../enums/enums.dart';

final List<ChildSPLDataPoint> childSPLData = [
  ChildSPLDataPoint(
    age: 0,
    centile: Centile.P50,
    heightCm: 67.0,
    weightKg: 7.7,
    penileLengthCm: 3.5,
    penileCircumferenceCm: 4.5,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 0,
    centile: Centile.P5,
    heightCm: 53.0,
    weightKg: 4.0,
    penileLengthCm: 2.8,
    penileCircumferenceCm: 3.5,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 0,
    centile: Centile.P95,
    heightCm: 77.0,
    weightKg: 10.94,
    penileLengthCm: 4.4,
    penileCircumferenceCm: 5.0,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 1,
    centile: Centile.P50,
    heightCm: 80.6,
    weightKg: 11.27,
    penileLengthCm: 3.7,
    penileCircumferenceCm: 4.5,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 1,
    centile: Centile.P5,
    heightCm: 73.0,
    weightKg: 8.53,
    penileLengthCm: 3.0,
    penileCircumferenceCm: 3.5,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 1,
    centile: Centile.P95,
    heightCm: 89.73,
    weightKg: 14.36,
    penileLengthCm: 4.6,
    penileCircumferenceCm: 5.2,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 2,
    centile: Centile.P50,
    heightCm: 91.5,
    weightKg: 14.0,
    penileLengthCm: 4.0,
    penileCircumferenceCm: 4.5,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 2,
    centile: Centile.P5,
    heightCm: 83.0,
    weightKg: 11.0,
    penileLengthCm: 3.0,
    penileCircumferenceCm: 3.7,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 2,
    centile: Centile.P95,
    heightCm: 99.73,
    weightKg: 17.54,
    penileLengthCm: 4.8,
    penileCircumferenceCm: 5.4,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 3,
    centile: Centile.P50,
    heightCm: 99.0,
    weightKg: 16.0,
    penileLengthCm: 4.0,
    penileCircumferenceCm: 4.7,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 3,
    centile: Centile.P5,
    heightCm: 91.67,
    weightKg: 13.0,
    penileLengthCm: 3.0,
    penileCircumferenceCm: 3.7,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 3,
    centile: Centile.P95,
    heightCm: 106.05,
    weightKg: 19.0,
    penileLengthCm: 5.0,
    penileCircumferenceCm: 5.5,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 4,
    centile: Centile.P50,
    heightCm: 105.95,
    weightKg: 17.92,
    penileLengthCm: 4.2,
    penileCircumferenceCm: 4.9,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 4,
    centile: Centile.P5,
    heightCm: 97.11,
    weightKg: 14.5,
    penileLengthCm: 3.2,
    penileCircumferenceCm: 3.7,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 4,
    centile: Centile.P95,
    heightCm: 114.45,
    weightKg: 23.0,
    penileLengthCm: 5.3,
    penileCircumferenceCm: 5.6,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 5,
    centile: Centile.P50,
    heightCm: 112.5,
    weightKg: 20.0,
    penileLengthCm: 4.5,
    penileCircumferenceCm: 5.0,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 5,
    centile: Centile.P5,
    heightCm: 104.28,
    weightKg: 16.0,
    penileLengthCm: 3.46,
    penileCircumferenceCm: 3.9,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 5,
    centile: Centile.P95,
    heightCm: 120.89,
    weightKg: 26.94,
    penileLengthCm: 5.5,
    penileCircumferenceCm: 6.0,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 6,
    centile: Centile.P50,
    heightCm: 119.0,
    weightKg: 22.0,
    penileLengthCm: 4.5,
    penileCircumferenceCm: 5.0,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 6,
    centile: Centile.P5,
    heightCm: 110.0,
    weightKg: 18.5,
    penileLengthCm: 3.5,
    penileCircumferenceCm: 4.0,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 6,
    centile: Centile.P95,
    heightCm: 127.09,
    weightKg: 28.89,
    penileLengthCm: 5.5,
    penileCircumferenceCm: 5.94,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 7,
    centile: Centile.P50,
    heightCm: 125.1,
    weightKg: 24.5,
    penileLengthCm: 4.6,
    penileCircumferenceCm: 5.2,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 7,
    centile: Centile.P5,
    heightCm: 115.0,
    weightKg: 19.0,
    penileLengthCm: 3.56,
    penileCircumferenceCm: 4.06,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 7,
    centile: Centile.P95,
    heightCm: 135.28,
    weightKg: 36.0,
    penileLengthCm: 6.0,
    penileCircumferenceCm: 6.2,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 8,
    centile: Centile.P50,
    heightCm: 130.4,
    weightKg: 27.5,
    penileLengthCm: 4.6,
    penileCircumferenceCm: 5.3,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 8,
    centile: Centile.P5,
    heightCm: 120.26,
    weightKg: 21.0,
    penileLengthCm: 3.7,
    penileCircumferenceCm: 4.1,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 8,
    centile: Centile.P95,
    heightCm: 140.45,
    weightKg: 40.72,
    penileLengthCm: 6.0,
    penileCircumferenceCm: 6.3,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 9,
    centile: Centile.P50,
    heightCm: 136.05,
    weightKg: 30.0,
    penileLengthCm: 4.6,
    penileCircumferenceCm: 5.4,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 9,
    centile: Centile.P5,
    heightCm: 125.0,
    weightKg: 24.0,
    penileLengthCm: 3.61,
    penileCircumferenceCm: 4.2,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 9,
    centile: Centile.P95,
    heightCm: 146.5,
    weightKg: 44.72,
    penileLengthCm: 5.89,
    penileCircumferenceCm: 6.44,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 10,
    centile: Centile.P50,
    heightCm: 141.55,
    weightKg: 34.0,
    penileLengthCm: 4.8,
    penileCircumferenceCm: 5.5,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 10,
    centile: Centile.P5,
    heightCm: 129.82,
    weightKg: 27.0,
    penileLengthCm: 3.66,
    penileCircumferenceCm: 4.5,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 10,
    centile: Centile.P95,
    heightCm: 152.63,
    weightKg: 53.0,
    penileLengthCm: 6.0,
    penileCircumferenceCm: 6.5,
    rightTestisVolumeMl: 4.0,
    leftTestisVolumeMl: 4.0,
  ),
  ChildSPLDataPoint(
    age: 11,
    centile: Centile.P50,
    heightCm: 146.55,
    weightKg: 37.75,
    penileLengthCm: 5.0,
    penileCircumferenceCm: 5.8,
    rightTestisVolumeMl: 3.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 11,
    centile: Centile.P5,
    heightCm: 135.46,
    weightKg: 28.28,
    penileLengthCm: 4.0,
    penileCircumferenceCm: 4.56,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 11,
    centile: Centile.P95,
    heightCm: 158.89,
    weightKg: 56.22,
    penileLengthCm: 6.9,
    penileCircumferenceCm: 7.24,
    rightTestisVolumeMl: 6.9,
    leftTestisVolumeMl: 6.0,
  ),
  ChildSPLDataPoint(
    age: 12,
    centile: Centile.P50,
    heightCm: 150.6,
    weightKg: 42.0,
    penileLengthCm: 5.6,
    penileCircumferenceCm: 6.4,
    rightTestisVolumeMl: 4.0,
    leftTestisVolumeMl: 4.0,
  ),
  ChildSPLDataPoint(
    age: 12,
    centile: Centile.P5,
    heightCm: 139.56,
    weightKg: 30.78,
    penileLengthCm: 4.0,
    penileCircumferenceCm: 4.76,
    rightTestisVolumeMl: 1.0,
    leftTestisVolumeMl: 1.0,
  ),
  ChildSPLDataPoint(
    age: 12,
    centile: Centile.P95,
    heightCm: 165.09,
    weightKg: 62.45,
    penileLengthCm: 8.8,
    penileCircumferenceCm: 9.04,
    rightTestisVolumeMl: 12.0,
    leftTestisVolumeMl: 12.0,
  ),
  ChildSPLDataPoint(
    age: 13,
    centile: Centile.P50,
    heightCm: 159.1,
    weightKg: 48.5,
    penileLengthCm: 7.25,
    penileCircumferenceCm: 7.9,
    rightTestisVolumeMl: 8.0,
    leftTestisVolumeMl: 8.0,
  ),
  ChildSPLDataPoint(
    age: 13,
    centile: Centile.P5,
    heightCm: 145.37,
    weightKg: 34.0,
    penileLengthCm: 4.5,
    penileCircumferenceCm: 5.1,
    rightTestisVolumeMl: 2.0,
    leftTestisVolumeMl: 2.0,
  ),
  ChildSPLDataPoint(
    age: 13,
    centile: Centile.P95,
    heightCm: 173.4,
    weightKg: 75.45,
    penileLengthCm: 9.5,
    penileCircumferenceCm: 10.0,
    rightTestisVolumeMl: 15.0,
    leftTestisVolumeMl: 15.0,
  ),
  ChildSPLDataPoint(
    age: 14,
    centile: Centile.P50,
    heightCm: 166.0,
    weightKg: 55.75,
    penileLengthCm: 8.0,
    penileCircumferenceCm: 8.8,
    rightTestisVolumeMl: 10.0,
    leftTestisVolumeMl: 10.0,
  ),
  ChildSPLDataPoint(
    age: 14,
    centile: Centile.P5,
    heightCm: 150.76,
    weightKg: 39.0,
    penileLengthCm: 5.56,
    penileCircumferenceCm: 6.5,
    rightTestisVolumeMl: 5.0,
    leftTestisVolumeMl: 4.0,
  ),
  ChildSPLDataPoint(
    age: 14,
    centile: Centile.P95,
    heightCm: 177.5,
    weightKg: 80.0,
    penileLengthCm: 10.0,
    penileCircumferenceCm: 10.5,
    rightTestisVolumeMl: 20.0,
    leftTestisVolumeMl: 15.0,
  ),
  ChildSPLDataPoint(
    age: 15,
    centile: Centile.P50,
    heightCm: 170.35,
    weightKg: 60.0,
    penileLengthCm: 8.7,
    penileCircumferenceCm: 9.0,
    rightTestisVolumeMl: 12.0,
    leftTestisVolumeMl: 12.0,
  ),
  ChildSPLDataPoint(
    age: 15,
    centile: Centile.P5,
    heightCm: 156.67,
    weightKg: 45.28,
    penileLengthCm: 7.0,
    penileCircumferenceCm: 7.2,
    rightTestisVolumeMl: 8.0,
    leftTestisVolumeMl: 6.0,
  ),
  ChildSPLDataPoint(
    age: 15,
    centile: Centile.P95,
    heightCm: 182.83,
    weightKg: 83.45,
    penileLengthCm: 10.5,
    penileCircumferenceCm: 11.0,
    rightTestisVolumeMl: 20.0,
    leftTestisVolumeMl: 20.0,
  ),
  ChildSPLDataPoint(
    age: 16,
    centile: Centile.P50,
    heightCm: 171.85,
    weightKg: 63.25,
    penileLengthCm: 9.0,
    penileCircumferenceCm: 9.25,
    rightTestisVolumeMl: 15.0,
    leftTestisVolumeMl: 12.0,
  ),
  ChildSPLDataPoint(
    age: 16,
    centile: Centile.P5,
    heightCm: 162.0,
    weightKg: 50.0,
    penileLengthCm: 7.2,
    penileCircumferenceCm: 7.66,
    rightTestisVolumeMl: 8.0,
    leftTestisVolumeMl: 8.0,
  ),
  ChildSPLDataPoint(
    age: 16,
    centile: Centile.P95,
    heightCm: 182.94,
    weightKg: 85.0,
    penileLengthCm: 11.0,
    penileCircumferenceCm: 10.94,
    rightTestisVolumeMl: 20.0,
    leftTestisVolumeMl: 20.0,
  ),
  ChildSPLDataPoint(
    age: 17,
    centile: Centile.P50,
    heightCm: 173.7,
    weightKg: 68.0,
    penileLengthCm: 9.0,
    penileCircumferenceCm: 9.5,
    rightTestisVolumeMl: 15.0,
    leftTestisVolumeMl: 13.5,
  ),
  ChildSPLDataPoint(
    age: 17,
    centile: Centile.P5,
    heightCm: 164.27,
    weightKg: 54.28,
    penileLengthCm: 7.41,
    penileCircumferenceCm: 8.0,
    rightTestisVolumeMl: 10.0,
    leftTestisVolumeMl: 10.0,
  ),
  ChildSPLDataPoint(
    age: 17,
    centile: Centile.P95,
    heightCm: 185.29,
    weightKg: 90.0,
    penileLengthCm: 11.0,
    penileCircumferenceCm: 11.1,
    rightTestisVolumeMl: 25.0,
    leftTestisVolumeMl: 20.0,
  ),
  ChildSPLDataPoint(
    age: 18,
    centile: Centile.P50,
    heightCm: 174.35,
    weightKg: 69.0,
    penileLengthCm: 9.0,
    penileCircumferenceCm: 9.2,
    rightTestisVolumeMl: 15.0,
    leftTestisVolumeMl: 15.0,
  ),
  ChildSPLDataPoint(
    age: 18,
    centile: Centile.P5,
    heightCm: 164.46,
    weightKg: 53.78,
    penileLengthCm: 7.5,
    penileCircumferenceCm: 7.96,
    rightTestisVolumeMl: 10.0,
    leftTestisVolumeMl: 10.0,
  ),
  ChildSPLDataPoint(
    age: 18,
    centile: Centile.P95,
    heightCm: 184.51,
    weightKg: 88.45,
    penileLengthCm: 11.0,
    penileCircumferenceCm: 11.0,
    rightTestisVolumeMl: 25.0,
    leftTestisVolumeMl: 20.0,
  ),
  ChildSPLDataPoint(
    age: 19,
    centile: Centile.P50,
    heightCm: 173.5,
    weightKg: 69.5,
    penileLengthCm: 9.5,
    penileCircumferenceCm: 9.5,
    rightTestisVolumeMl: 15.0,
    leftTestisVolumeMl: 15.0,
  ),
  ChildSPLDataPoint(
    age: 19,
    centile: Centile.P5,
    heightCm: 163.17,
    weightKg: 57.0,
    penileLengthCm: 8.0,
    penileCircumferenceCm: 8.2,
    rightTestisVolumeMl: 10.0,
    leftTestisVolumeMl: 10.0,
  ),
  ChildSPLDataPoint(
    age: 19,
    centile: Centile.P95,
    heightCm: 184.0,
    weightKg: 89.45,
    penileLengthCm: 11.0,
    penileCircumferenceCm: 11.35,
    rightTestisVolumeMl: 25.0,
    leftTestisVolumeMl: 25.0,
  ),
];