import "../milk.dart";

final List<Milk> milks = [
  Milk(name: "Aptamil 1 First Milk", carbsPer100ml: 7.0),
  Milk(name: "Aptamil Profutura 1 First Infant Milk", carbsPer100ml: 7.0),
  Milk(name: "Breast Milk (mature)", carbsPer100ml: 7.2),
  Milk(name: "Cow & Gate 1 First Infant Milk", carbsPer100ml: 7.4),
  Milk(name: "Hipp Organic Combiotic First Infant Milk", carbsPer100ml: 7.3),
  Milk(name: "Holle Organic Infant Formula 1", carbsPer100ml: 7.4),
  Milk(name: "SMA Pro First Infant Milk", carbsPer100ml: 7.1),
  Milk(name: "Holle Organic Infant Goat Milk Formula 1", carbsPer100ml: 7.5),
  Milk(name: "Kabrita Gold 1", carbsPer100ml: 7.3),
  Milk(name: "NANNYcare First Infant Milk", carbsPer100ml: 7.4),
  Milk(name: "Aptamil Hungry Milk", carbsPer100ml: 7.8),
  Milk(name: "Cow & Gate Infant Milk for Hungrier Babies", carbsPer100ml: 7.8),
  Milk(name: "Hipp Organic Combiotic Hungry Infant Milk", carbsPer100ml: 7.3),
  Milk(name: "SMA Extra Hungry", carbsPer100ml: 7.0),
  Milk(name: "Aptamil Anti-reflux", carbsPer100ml: 6.8),
  Milk(name: "Cow & Gate Anti-reflux", carbsPer100ml: 6.8),
  Milk(name: "SMA Staydown", carbsPer100ml: 7.0),
  Milk(name: "SMA Wysoy", carbsPer100ml: 6.9),
  Milk(name: "Aptamil Lactose Free", carbsPer100ml: 7.3),
  Milk(name: "Aptamil Comfort", carbsPer100ml: 7.2),
  Milk(name: "Cow & Gate Comfort", carbsPer100ml: 7.2),
  Milk(name: "SMA Comfort", carbsPer100ml: 7.1),
  Milk(name: "SMA HA", carbsPer100ml: 7.8),
  Milk(name: "Aptamil 2 Follow-on Milk", carbsPer100ml: 8.6),
  Milk(name: "Aptamil Profutura 2 Follow-on Milk", carbsPer100ml: 8.8),
  Milk(name: "Cow & Gate 2 Follow-on Milk", carbsPer100ml: 8.6),
  Milk(name: "Hipp Organic Combiotic Follow-on Milk", carbsPer100ml: 7.9),
  Milk(name: "Holle Organic Infant Follow-on Formula", carbsPer100ml: 8.2),
  Milk(name: "SMA Pro Follow-on Milk", carbsPer100ml: 7.9),
  Milk(name: "Holle Organic Infant Goat Milk Follow-on Formula 2", carbsPer100ml: 8.0),
  Milk(name: "Kabrita Gold 2", carbsPer100ml: 8.0),
  Milk(name: "NANNYcare Follow-on Milk", carbsPer100ml: 7.4),
  Milk(name: "Hipp Organic Good Night Milk", carbsPer100ml: 8.0),
  Milk(name: "Full-fat cows milks", carbsPer100ml: 4.6),
  Milk(name: "Semi-skimmed cows Milk", carbsPer100ml: 4.7),
  Milk(name: "Aptamil 3 Growing Up Milk 1-2 Years", carbsPer100ml: 8.5),
  Milk(name: "Aptamil Profutura 3 Growing Up Milk", carbsPer100ml: 8.4),
  Milk(name: "Cow & Gate 3 Growing Up Name 1-2 Years", carbsPer100ml: 8.5),
  Milk(name: "Hipp Organic Combiotic Growing-up Milk", carbsPer100ml: 8.2),
  Milk(name: "Holle Organic Growing-up Milk 3", carbsPer100ml: 8.2),
  Milk(name: "PaediaSure Shake", carbsPer100ml: 13.2),
  Milk(name: "SMA Pro Toddler Milk 3", carbsPer100ml: 7.0),
  Milk(name: "Kabrita Gold 3", carbsPer100ml: 7.9),
  Milk(name: "NANNYcare Growing Up Milk", carbsPer100ml: 6.7),
  Milk(name: "Alpro Soya +1 Complete Care", carbsPer100ml: 8.3),
  Milk(name: "Aptamil 4 Growing Up Milk 2-3 Years", carbsPer100ml: 6.5),
  Milk(name: "Cow & Gate 4 Growing Up Milk 2-3 Years", carbsPer100ml: 6.5),
  Milk(name: "Aptamil Pepti 1", carbsPer100ml: 7.1),
  Milk(name: "Cow & Gate Pepti-junior", carbsPer100ml: 6.8),
  Milk(name: "Mead Johnson Nutramigen LIPIL 1", carbsPer100ml: 7.5),
  Milk(name: "SHS Nutricia Pepdite", carbsPer100ml: 7.8),
  Milk(name: "SHS Nutricia Pepdite MCT", carbsPer100ml: 8.8),
  Milk(name: "SHS Nutricia Infatrini Peptisorb", carbsPer100ml: 10.3),
  Milk(name: "Aptamil Pepti 2", carbsPer100ml: 8.0),
  Milk(name: "Mead Johnson Pregestimil LIPIL", carbsPer100ml: 6.9),
  Milk(name: "Mead Johnson Nutramigen LIPIL 2", carbsPer100ml: 8.6),
  Milk(name: "SHS Nutricia Pepdite 1+", carbsPer100ml: 13.0),
  Milk(name: "SHS Nutricia Pepdite MCT 1+", carbsPer100ml: 11.8),
  Milk(name: "Mead Johnson Nutramigen AA", carbsPer100ml: 7.0),
  Milk(name: "SHS Nutricia Neocate LCP", carbsPer100ml: 7.2),
  Milk(name: "SHS Nutricia GA1 Anamix Infant", carbsPer100ml: 7.4),
  Milk(name: "SHS Nutricia HCU Anamix Infant", carbsPer100ml: 7.4),
  Milk(name: "SHS Nutricia IVA Anamix Infant", carbsPer100ml: 7.4),
  Milk(name: "SHS Nutricia MMA/PA Anamix Infant", carbsPer100ml: 7.4),
  Milk(name: "SHS Nutricia MSUD Anamix Infant", carbsPer100ml: 7.4),
  Milk(name: "SHS Nutricia NKH Anamix Infant", carbsPer100ml: 7.3),
  Milk(name: "SHS Nutricia TYR Anamix Infant", carbsPer100ml: 7.3),
  Milk(name: "Vitaflo PKU start", carbsPer100ml: 8.3),
  Milk(name: "Abbott Nutrition Similac High Energy", carbsPer100ml: 10.3),
  Milk(name: "SHS Nutricia Infatrini", carbsPer100ml: 10.3),
  Milk(name: "SMA High Energy", carbsPer100ml: 9.8),
  Milk(name: "Mead Johnson Enfamil AR", carbsPer100ml: 7.6),
  Milk(name: "Cow & Gate Infasoy", carbsPer100ml: 7.0),
  Milk(name: "SMA Wysoy", carbsPer100ml: 6.9),
  Milk(name: "Mead Johnson Enfamil O-Lac", carbsPer100ml: 7.2),
  Milk(name: "SMA LF", carbsPer100ml: 7.2),
  Milk(name: "Aptamil Preterm", carbsPer100ml: 8.4),
  Milk(name: "Cow & Gate Nutriprem 1", carbsPer100ml: 8.4),
  Milk(name: "SMA Gold Prem 1", carbsPer100ml: 8.4),
  Milk(name: "Cow & Gate Nutriprem 2", carbsPer100ml: 7.5),
  Milk(name: "SMA Gold Prem 2", carbsPer100ml: 7.5),
  Milk(name: "SHS Nutricia Caprilon", carbsPer100ml: 7.0),
  Milk(name: "SHS Nutricia Monogen", carbsPer100ml: 12.0),
  Milk(name: "Vitaflo Lipistart", carbsPer100ml: 8.3),
  Milk(name: "SHS Nutricia Galactomin 17", carbsPer100ml: 7.3),
  Milk(name: "SHS Nutricia Galactomin 19", carbsPer100ml: 6.4),
  Milk(name: "SHS Nutricia Kindergen", carbsPer100ml: 11.8),
  Milk(name: "Vitaflo Renastart", carbsPer100ml: 12.5),
];

List<Milk> sortedMilks(List<Milk> milks) {
  List<Milk> sorted =  List.from(milks);
  sorted.sort((a, b) => a.name.compareTo(b.name));
  return sorted;
}